tap "github/bootstrap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "martido/brew-graph"
tap "vapor/tap"
brew "ansible"
brew "autoconf"
brew "carthage"
brew "dockutil"
brew "exa"
brew "fd"
brew "fish"
brew "fork-cleaner"
brew "git-lfs"
brew "git"
brew "heroku/brew/heroku"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "jq"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "libtool"
brew "mackup"
brew "martido/brew-graph/brew-graph"
brew "mas"
brew "openssl"
brew "pcre2"
brew "pkg-config"
brew "pngquant"
brew "rbenv-default-gems"
brew "rbenv"
brew "ripgrep"
brew "ruby-build"
brew "ruby"
brew "ruby@2.5"
brew "shellcheck"
brew "speedtest-cli"
brew "ssh-copy-id"
brew "vapor/tap/vapor"
brew "wget"
brew "yarn"
brew "z"
cask "1password-cli"
cask "alfred"
cask "appcleaner"
cask "arq"
cask "bitbar"
cask "docker"
cask "firefox"
cask "flux"
cask "font-meslo-for-powerline"
cask "gpg-suite-no-mail"
cask "handbrake"
cask "iterm2"
cask "java"
cask "little-snitch"
cask "logitech-gaming-software"
cask "nextcloud"
cask "provisionql"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "rescuetime"
cask "setapp"
cask "skala-preview"
cask "sketch"
cask "slack"
cask "spotify"
cask "tower"
cask "visual-studio-code"
cask "vlc"
mas "com.agilebits.onepassword7", id: 1333542190
mas "com.apple.dt.Xcode", id: 497799835
mas "com.apple.iWork.Keynote", id: 409183694
mas "com.blackmagic-design.DiskSpeedTest", id: 425264550
mas "com.brettterpstra.marked2", id: 890031187
mas "com.culturedcode.ThingsMac", id: 904280696
mas "com.fittschen.IsItPrivate", id: 1440322906
mas "com.Growl.GrowlHelperApp", id: 467939042
mas "com.if.Amphetamine", id: 937984704
mas "com.khanov.BlockerMac", id: 1107421413
mas "com.oneminutegames.XcodeCleaner", id: 1388020431
mas "com.ookla.speedtest-macos", id: 1153157709
mas "com.overmacs.photosweeper", id: 463362050
mas "com.seriflabs.affinityphoto", id: 824183456
mas "com.stoegerit.outbank.osx", id: 1094255754
mas "com.vidblishen.jsonhelper", id: 453114608
mas "cx.c3.theunarchiver", id: 425424353
mas "io.raindrop.mac", id: 957810159
