#!/usr/bin/env bash
set -e

if ! [ -L ~/.gnupg ] || ! [ -L ~/.ssh ]
then
  echo "Run script/setup first!" >&2
  exit 1
fi

onepassword_login() {
  if ! command -v op >/dev/null
  then
    echo "Install op first!" >&2
    exit 1
  fi

  # shellcheck disable=SC2154
  if [ -z "$OP_SESSION_my" ]
  then
    echo "Logging into 1Password..."
    eval "$(op signin my.1password.com ffittschen@gmail.com)"
  fi
}

onepassword_get() {
  if [ -f "$HOME/$2" ]
  then
    echo "$2 already exists."
    return
  fi
  echo "Extracting $2..."
  onepassword_login
  op get document "$1" > "$HOME/$2"
  chmod 600 "$HOME/$2"
}

onepassword_get psooa7lvlvbd5pbfk5fhwznhja .ssh/id_ed25519
onepassword_get xb4nvtbnlvd3thu77frb6tgg4i .ssh/id_rsa
onepassword_get jxeeyb6dpje6pcruffbjv74l7u .gnupg/ffittschen@gmail.com.private.gpg-key

echo "Storing SSH keys in keychain..."
ssh-add -K

echo "Setting up GPG..."
if ! command -v gpg >/dev/null
then
    echo "Install GPG first!" >&2
    exit 1
fi

chmod 700 ~/.gnupg
gpg --import ~/.gnupg/ffittschen@gmail.com.public.gpg-key \
             ~/.gnupg/ffittschen@gmail.com.private.gpg-key
