alias lsa "ls -Alh"
alias be "bundle exec"
alias g "gittower ."
alias o "open ."
alias bu "brew update; and brew upgrade; and brew cleanup"
alias certs "env MATCH_KEYCHAIN_PASSWORD=(read -s) bundle exec fastlane certificates"
alias pr "git push origin HEAD && open (gh pr create -f)"
alias mr "mise run"
alias o3 "orka3"
